name: Build Eclipse Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Show folder structure
      run: |
        pwd
        ls -lat
        df -h
        ls
    - name: Install OpenJDK 21
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jdk  # Installiere OpenJDK 21
    
    - name: Install X virtual frame buffer (XVFB)
      run: |
        sudo apt-get install xvfb

    - name: Verify Java Version
      run: |
        java -version  # Überprüfe, ob OpenJDK 21 korrekt installiert ist

    - name: Install Eclipse IDE
      run: |
        # Download und installiere Eclipse
        wget -qO- https://download.eclipse.org/technology/epp/downloads/release/2023-09/R/eclipse-java-2023-09-R-linux-gtk-x86_64.tar.gz | tar xz --no-same-owner -C /opt
        # Erstelle einen Symlink, damit Eclipse im PATH verfügbar ist
        sudo ln -s /opt/eclipse/eclipse /usr/local/bin/eclipse

    - name: Build Plugin using Eclipse PDE
      run: |
        cd path/to/your/eclipse/plugin/project
        xvfb-run eclipse -nosplash -application org.eclipse.pde.Build -build path/to/your/buildfile -headless -Dorg.eclipse.swt.internal.gtk.disableX11=true
        
    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: my-application.jar
